
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package edu.robertob.p2compi1.models;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TAG_CLOSE = 4;
  public static final int TAGS_NAME = 11;
  public static final int ACTION_TAG_NAME = 6;
  public static final int VALUE_ATTR = 13;
  public static final int ATTR_TAG_NAME = 18;
  public static final int ATTRS_TAG_NAME = 19;
  public static final int ID = 15;
  public static final int NAME_ATTR = 12;
  public static final int PARAM_VALUE = 17;
  public static final int EQUALS = 14;
  public static final int ACTIONS_TAG_NAME = 7;
  public static final int EOF = 0;
  public static final int TAG_END = 3;
  public static final int PARAMS_TAG_NAME = 9;
  public static final int TAG_START = 2;
  public static final int TAG_NAME = 10;
  public static final int PARAM_TAG_NAME = 8;
  public static final int error = 1;
  public static final int TAG_SELF_CLOSE = 5;
  public static final int ATTR_VALUE = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TAG_START",
  "TAG_END",
  "TAG_CLOSE",
  "TAG_SELF_CLOSE",
  "ACTION_TAG_NAME",
  "ACTIONS_TAG_NAME",
  "PARAM_TAG_NAME",
  "PARAMS_TAG_NAME",
  "TAG_NAME",
  "TAGS_NAME",
  "NAME_ATTR",
  "VALUE_ATTR",
  "EQUALS",
  "ID",
  "ATTR_VALUE",
  "PARAM_VALUE",
  "ATTR_TAG_NAME",
  "ATTRS_TAG_NAME"
  };
}

